### ISSUE TITLE
[Axway]: 0 jobs returned on peviitor.ro whereas 9 jobs are available on the company's website.

### ISSUE THREAD

**Issue by redandreea** [peviitor-ro/Scrapers_start_with_digi#11]
**ENVIRONMENT**: PROD
url: https://peviitor.ro/
browser: Google Chrome Version 114.0.5735.199 (Official Build) (64-bit)
device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open url in browser
2. Type  " Axway" in the Search Box placeholder
3. Click on "Cauta" button
4. Pay attention to the search results message
5. Go to Axway website : https://careers-axway.icims.com/jobs/search?ss=1&searchLocation=13526--Bucharest&mobile=false&width=1268&height=500&bga=true&needsRedirect=false&jan1offset=120&jun1offset=180
6. Check the number of jobs from Axway
7. Compare the number of jobs Axway have with numbers of jobs peviitor.ro have

**EXPECTED RESULTS:**

Number of jobs  on peviitor.ro matches the number of jobs available on company's website.

**ACTUAL RESULTS:**

0 jobs returned on peviitor.ro whereas 9 jobs are available on the company's website.

![axway 0 jobs](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/120127181/0539f91f-c704-45cd-ae72-f308df128571)
![axway bug](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/120127181/20761747-1e30-4b78-a5a3-ff55aecbd0e0)
![axway bug](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/120127181/a7816d54-bdea-4808-85b6-72787301810c)

**Comment by sebiboga** [comment]
retested in PROD
this issue has been fixed
closing the bug
