### ISSUE TITLE
RESTARTENERGY - See jobs button

### ISSUE THREAD

**Issue by simina1606** [peviitor-ro/Scrapers_start_with_digi#147]
Environment: Production
URL : https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS : Windows 10

Steps to reproduce:

1. Open URL in browser.
2. Write in the search bar : Restartenergy.
3. Click on : Restartenergy.
4. Click on the "See jobs" button.
5. The www.peviitor.ro page is displayed.

Expected result:
The jobs are displayed on www.peviitor.ro page.

Actual result:
No jobes are displayed on www.peviitor.ro

![image](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/156781906/32260483-0d3b-4bce-9f48-cfb3d224187a)

**Comment by lalalaurentiu** [comment]
@andreireporter13 Asta nu e datoria mea
