### ISSUE TITLE
ROMSOFT - See jobs button

### ISSUE THREAD

**Issue by simina1606** [peviitor-ro/Scrapers_start_with_digi#150]
Environment: Production
URL : https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS : Windows 10

Steps to reproduce:
1. Open URL in browser.
2. Write in the search bar : Romsoft.
3. Click on : Romsoft.
4. Click on "See jobs" button.
5. The www.peviitor.ro page is displayed.

Expected result:
The jobs are displayed on www.peviitor.ro

Actual result:
No jobs are displayed on www.peviitor.ro

![image](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/156781906/a2f969a5-da56-41f7-a2d0-334925beb37e)

**Comment by lalalaurentiu** [comment]
@andreireporter13 Asta nu e datoria mea
