### ISSUE TITLE
SBAFELX - See jobs button

### ISSUE THREAD

**Issue by simina1606** [peviitor-ro/Scrapers_start_with_digi#158]
Environment: Production
URL : https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS : Windows 10

Steps to reproduce:
1. Open URL in browser.
2. Write in the search bar : sbafelx
3. Click on : sbaflex
4. Click on "See jobs" button.
5. The www.peviitor.ro page is displayed.

Expected result:
The jobs are displayed on www.peviitor.ro page.

Actual result:
No jobs are displayed on www.peviitor.ro page.

![image](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/156781906/5a92d6ac-5df7-4a56-bd9b-5d6d8c2a6742)

**Comment by lalalaurentiu** [comment]
@andreireporter13 Asta nu e bug pentru mine
