### ISSUE TITLE
SIEMENS - "See jobs" button

### ISSUE THREAD

**Issue by simina1606** [peviitor-ro/Scrapers_start_with_digi#163]
Environment: Production
URL : https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS : Windows 10

Steps to reproduce:
1. Open URL in browser.
2. Write in the search bar : siemens.
3. Click on : siemens.
4. Click on "See jobs" button.
5. The www.peviitor.ro page is displayed.

Expected result:
The jobs are displayed on www.peviitor.ro page.

Actual result:
No jobs are displayed on www.peviitor.ro page.

![see jobs button](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/156781906/8eaa55cc-1849-40cf-8f1e-db899e20effa)

**Comment by lalalaurentiu** [comment]
@andreireporter13 Asta nu depinde de mine
