### ISSUE TITLE
SITA - "See jobs" button

### ISSUE THREAD

**Issue by simina1606** [peviitor-ro/Scrapers_start_with_digi#170]
Environment: Production
URL : https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS : Windows 10

Steps to reproduce:
1. Open URL in browser.
2. Write in the search bar : Sita.
3. Click on : Sita.
4. Click on "See jobs" button.
5. The www.peviitor.ro page is displayed.

Expected result:
The jobs are displayed on www.peviitor.ro page.

Actual result:
No jobs are displayed on www.peviitor.ro page.

**Comment by lalalaurentiu** [comment]
@andreireporter13 Asta nu depinde de mine
