### ISSUE TITLE
SMARTDREAMERS - "See jobs" button

### ISSUE THREAD

**Issue by simina1606** [peviitor-ro/Scrapers_start_with_digi#176]
Environment: Production
URL : https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS : Windows 10

Steps to reproduce:
1. Open URL in browser.
2. Write in the search bar : Smartdreamers.
3. Click on : Smartdreamers.
4. Click on "See jobs" button.
5. The www.peviitor.ro page is displayed.

Expected result:
The jobs are displayed on www.peviitor.ro page.

Actual result:
No jobs are displayed on www.peviitor.ro page.

![see jobs button](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/156781906/5c1f1fa4-5824-49f1-a3ac-9c3aba905915)

**Comment by lalalaurentiu** [comment]
@andreireporter13 Asta nu depinde de mine
