### ISSUE TITLE
Wirtek-Cities displayed on https://scrapers.peviitor.ro/ are not the same as cities displayed on the Wiretek website.

### ISSUE THREAD

**Issue by cristiol** [peviitor-ro/Scrapers_start_with_digi#20]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 

STEPS TO REPRODUCE:

1) Open "https://scrapers.peviitor.ro/"
2) Type "wirtek" in the search bar.
3) Check the location.
![wirtek_peviitor](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/142798921/5781a58c-8bea-4be3-8990-d891fa3dc44b)

4) Open the link "https://www.wirtek.com/careers".
5) Check the location.

![wirtek_site](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/142798921/018433c8-573b-48b6-ad07-10873924cfbe)

EXPECTED RESULTS:

The location for each job displayed on "https://scrapers.peviitor.ro/" should be the same as the ones displayed on "https://www.wirtek.com/careers."

ACTUAL RESULT:

On "https://scrapers.peviitor.ro/" for each job, the location displayed is "Romania" but on "https://www.wirtek.com/careers" the jobs have different locations ("remote", "Cluj-Napoca," "Bucharest".

**Comment by andreireporter13** [comment]
Done!
