### ISSUE TITLE
Crosswork - Two logos displayed for the same company

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/Scrapers_start_with_digi#205]
ENVIROMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type "crosswork" in the search bar

EXPECTED RESULTS:
The logo company must be displayed only once.

ACTUAL RESULTS:
There are displayed two companies with the same name.
![crosswork](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/143128512/eeacd31c-1042-4b3e-b7ff-d5a4816610fc)

**Comment by DiannaAN** [comment]
_This bug persists despite a recent examination of the company Crosswork._
![crosswork peviitor ro - listat de 2 ori](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/143723484/3f96583d-e0ab-42d4-9b5c-5eef7f908f78)

**Comment by DiannaAN** [comment]
_This bug persists despite a recent examination of the company Crosswork._
![(posted) crosswork peviitor ro - listat de 2 ori](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/143723484/9da60833-fdbe-494e-bcee-ed0ae6f1746b)
