### ISSUE TITLE
Globallagic: The number of jobs displayed on Peviitor (0) and the ones displayed on the company website (66) aren't the same.

### ISSUE THREAD

**Issue by cristiol** [peviitor-ro/Scrapers_start_with_digi#24]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 

STEPS TO REPRODUCE:

1) Open "https://peviitor.ro/" in the browser.
2) Type "Globallogic" in the search bar.
3) Check the number of jobs available for "Globallogic".
4) Open "https://www.globallogic.com/ro/career-search-page/?keywords=&experience=&locations=romania&c=".
5) Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs displayed on "https://peviitor.ro/" and the number of jobs displayed on the company website should be the same.

ACTUAL RESULT:
There are 0 jobs displayed on Peviitor website, while on the company website there are displayed 66 available jobs.

![gloaballogic_peviitor](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/142798921/222a122a-9d9c-400b-8f78-8a14e353bcac)

![gloaballogic_site](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/142798921/6b67fe94-3b50-4cfc-8fe5-643e9c2e6803)

**Comment by andreireporter13** [comment]
This site is parked.
