### ISSUE TITLE
Missing jobs  from APPGREAT Company we have 12 but should be 14 jobs

### ISSUE THREAD

**Issue by BogdanScutariu** [peviitor-ro/Scrapers_start_with_digi#26]
Environment: Windows
url: https://scrapers.peviitor.ro/src/appgreat/index.html
https://peviitor.ro/rezultate?q=AppGreat&country=Rom%C3%A2nia&page=1
Browser  : Chrome
 
Steps:
1)Open url in the browser 
2) type "Appgreat" on the search bar 
3) Check how many jobs we have

Expected results: 
We should have 14 jobs showed

![Screenshot (25)](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/139114218/8957626c-d00f-478a-88ab-30ec4bb5f10b)

Actual results : we have only 12 jobs on the url.
![Screenshot (26)](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/139114218/024aff3b-93ba-4034-ad00-de28eec6304e)
![Screenshot (27)](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/139114218/8a9f6586-442d-4b61-b3e5-9212506fcac9)

**Comment by andreireporter13** [comment]
No bug. 2 jobs on the company site have 404 error.
