### ISSUE TITLE
AUSY SCRAPER is not loading the results after pressing Run Scraper

### ISSUE THREAD

**Issue by BogdanScutariu** [peviitor-ro/Scrapers_start_with_digi#27]
Environment: Windows
URL : https://scrapers.peviitor.ro/src/ausy/index.html
Browser : Chrome

Steps:
1)Open url in the browser
2) type "Appgreat" on the search bar
3) We press Run Scraper 

Expected results:
We should see more information with what jobs are available 
![Screenshot (29)](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/139114218/dac52bde-364e-47d9-9e77-73b923d0dfa4)

Actual result: The Scraper is not loading, Logo is not loading 
![Screenshot (29)](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/139114218/dac52bde-364e-47d9-9e77-73b923d0dfa4)
![Screenshot (28)](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/139114218/02397bd0-dd06-499c-bf25-d7c8c387d3ba)

**Comment by danielastanculesc** [comment]
Same result.
There are 34 jobs available on the Ausy website.

![ausy2](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/143128512/ccc6c2d4-110c-4938-b2fd-fc1c6a6c918d)
