### ISSUE TITLE
Two logos displayed for the same company

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/Scrapers_start_with_digi#271]
ENVIROMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type the name of the company in the search bar

EXPECTED RESULTS:
The logo company must be displayed only once.

ACTUAL RESULTS:
There are displayed two logos with the same name for the companies below.
 - azets
 - bertrandtgroup
 - blackline
 - capex
 - citi
 - crosswork
 - daisler
 - egger
 - eurofins
 - evalueserve
 - everience
 - genos
 - osf

**Comment by andreireporter13** [comment]
Am sters firmele duplicates.
