### ISSUE TITLE
Systematic: The number of jobs displayed on "https://peviitor.ro/" (10) is not the same as the number of jobs displayed on the company site (12)

### ISSUE THREAD

**Issue by cristiol** [peviitor-ro/Scrapers_start_with_digi#28]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

Open "https://peviitor.ro/".
Type "Systematic" on the search bar.
Check the number of jobs displayed.
Open "https://jobs.systematic.com/search/?q=&sortColumn=referencedate&sortDirection=desc&optionsFacetsDD_country=RO&startrow=10".
Check the number of jobs displayed. 

EXPECTED RESULTS:

The number of jobs displayed on "https://peviitor.ro/" and the number of jobs displayed on the company website should be the same.

ACTUAL RESULT:

There are 10 jobs displayed on Peviitor website, while on the company website there are displayed 12 available jobs

![systematic_peviitor](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/142798921/f95769bd-8439-4f21-b9b5-c847d51ee07a)

![systematic_site](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/142798921/40522bf6-5bb9-4675-bdba-e2e51892cbf8)

**Comment by andreireporter13** [comment]
Done!
