### ISSUE TITLE
Eurofins - Jobs is not remote

### ISSUE THREAD

**Issue by Elena1303996** [peviitor-ro/Scrapers_start_with_digi#288]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10
STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Eurofins" in the search bar
3. Click "Run Scraper" button
4. Check if the jobs are remote

Expected result:
When we compare the location of jobs on our website with the location on the company website, we see the same thing.

Actual result:
All jobs are remote
![Untitled03](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/157009443/caf8c845-c418-4927-9494-75d6a8472f36)

**Comment by andreireporter13** [comment]
Remote vine din API.
