### ISSUE TITLE
BLAKLINE - Not the same number of jobs on scraper.UI and peviitor.ro

### ISSUE THREAD

**Issue by simina1606** [peviitor-ro/Scrapers_start_with_digi#292]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

Open URL in browser

1. Type "blackline" in the search bar.
2. Click on "Cauta" button

EXPECTED RESULTS:
2 jobs are displayed.

ACTUAL RESULT:
4 jobs are displayed.

![image](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/156781906/43b60514-80bc-427a-9cd4-712eccd62505)

![image](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/156781906/dbce1b15-d610-4cc8-85d5-d0637e3f0949)

**Comment by danielastanculesc** [comment]
This is not a bug. the company name is present in another company's job title.
