### ISSUE TITLE
CECBank Company - Scraper not found job listing discrepancies

### ISSUE THREAD

**Issue by DiannaAN** [peviitor-ro/Scrapers_start_with_digi#301]
Upon inspecting the company "_CECBank_" on our scraper, it was noticed that the scraper is labeled only as "_cec_". Upon further investigation using Postman, it was discovered that the scraper is not found. Additionally, discrepancies were found between the job openings listed on our website "_peviitor.ro_" and the main website of _CECBank_.

![cecbank scraper](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/143723484/2b86f2be-649b-4663-a5f9-60441ce0d2b4)

![cecbank peviitor ro](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/143723484/ae112a49-6370-4bc6-a8df-0fd9e2103a48)

**Steps to Reproduce**:
- Access the link: _https://scrapers.peviitor.ro/_
- Search for the company "_CECBank_" (listed as "cec" on the scraper).
- Right-click and inspect the page to obtain the Request URL.
- Copy the Request URL: _https://dev.laurentiumarian.ro/scraper/Scrapers_start_with_digi/_
- Check the Request Method, which is _POST._
- Open Postman and create a new entry with a _POST_ request.
- Observe the error message indicating "_Scraper not found._"

Further examine the discrepancies in job listings between "_peviitor.ro_" and the main website of _CECBank_.

**Observed Issues**:

- The scraper for "_CECBank_" is not found, likely due to it being labeled only as "_cec_" 
![cecbank postman](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/143723484/e59897f2-56fc-4d5a-9efc-eb9436e30af6)

- Discrepancies exist between the job openings listed on "_peviitor.ro_" and the main website of CECBank. The positions for "_Consilier back-up - Sucursala Arad_," "_Consilier tranzacții clienți - Agentia Pecica, Sucursala Arad_," and "_Telebanker - Serviciul Administrare Market Place, Direcția Operațiuni la Distanță_" are no longer available on the main website but are still listed on "peviitor.ro."
![cecbank anunt expirat](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/143723484/f2f5dcb5-c003-4032-99bd-287c394dd7a8)

- The location for the position "_Consilier Tranzacții Clienți - Miercurea Ciuc_" is listed as "_Ciuc_" on "_peviitor.ro_," whereas the main website specifies the location as "_Miercurea Ciuc - Odorheiu Secuiesc, Petofi Sandor, Harghita_."
![cecbank job location](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/143723484/a8b301c1-403a-4ebf-accf-3acf7f12dfe3)

**Comment by andreireporter13** [comment]
O sa ma ocup mai tarziu de Locatiile de aici si de CECBank.
