### ISSUE TITLE
Hpe - Bangalore is not a city in Romania

### ISSUE THREAD

**Issue by Elena1303996** [peviitor-ro/Scrapers_start_with_digi#307]
Environment: Production
URL : https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS : Windows 10

1. Open URL in browser
2. Type "Hpe" in the search bar
3. Click "Hpe" button
4. A new window is loaded https://scrapers.peviitor.ro/src/hpe/index.html
5. Click "Run Scraper" button
6. Check the type of jobs
7. Open carrers page of the company https://careers.hpe.com/us/en/search-results
8. Check the type of jobs

Expected result:
All jobs available on Scrapers.peviitor.ro, the location of the jobs is Bucuresti, as on the company website.

Actual result:
Error " Bangalore is not a city in Romania" is displayed.
![Untitledddddd](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/157009443/5461c953-3284-4512-ad9d-33cd0f2b6bf1)

**Comment by andreireporter13** [comment]
S-a rezolvat de la sine. :))
