### ISSUE TITLE
SIEMENS - Remote_local is displayed instead of Remote

### ISSUE THREAD

**Issue by simina1606** [peviitor-ro/Scrapers_start_with_digi#314]
Environment:

URL: https://peviitor.ro/
Browser: Microsoft Edge
Device: Desktop
OS: Windows 7

Steps to Reproduce:

1. Access the link: https://peviitor.ro/
2. Search for the given company: Siemens.
3. Check the locations of jobs.

Expected result:
Technical SAP EWM Consultant - Remote
Senior Cyber Security Architect - PKI - Remote
Senior Cyber Security Architect - IAM - Remote
Senior Research Scientist - Embedded Security Testing - Remote

Actual result:
Technical SAP EWM Consultant - Remote_local
Senior Cyber Security Architect - PKI - Remote_local
Senior Cyber Security Architect - IAM - Remote_local
Senior Research Scientist - Embedded Security Testing - Remote_local

![image](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/156781906/1346b6f9-5671-4f73-8fa5-ac5780374e8a)

**Comment by andreireporter13** [comment]
Fixed.
