### ISSUE TITLE
Capex - The locations of jobs from another country appear

### ISSUE THREAD

**Issue by Elena1303996** [peviitor-ro/Scrapers_start_with_digi#315]
ENVIROMENT: production
URL: peviitor.ro
Browser: Mozilla
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Capex" in the search bar.
3. Click on "Cauta" button
4. Right-click and then click the Inspect option
5. Click on "Network" Button
6. Click on "Fetch/XHR"
7. Right-click and copy as cURL(bash) the API URL
8. Go to Postman - add a new request, paste the link and click "SEND" button
9. Go to the Capex career page: https://portal.dynamicsats.com/JobListing/347022b3-2e4e-48d2-9dac-9f7d78675080
10. Check jobs location

EXPECTED RESULTS:
On the peviitor.ro website, there are jobs with locations from another country: Dubai, Abu-Dhabi.

ACTUAL RESULT:
All job locations are in Romania.

![Untitledsdsds](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/157009443/16b94390-1372-45c7-819d-00784311aa36)

**Comment by andreireporter13** [comment]
Fixed.
