### ISSUE TITLE
Idemia - The locations of jobs from another country appear

### ISSUE THREAD

**Issue by Elena1303996** [peviitor-ro/Scrapers_start_with_digi#317]
ENVIROMENT: production
URL: peviitor.ro
Browser: Mozilla
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1.	Open URL in browser
2.	Type "Idemia" in the search bar.
3.	Click on "Cauta" button
4.	Right-click and then click the Inspect option
5.	Click on "Network" Button
6.	Click on "Fetch/XHR"
7.	Right-click and copy as cURL(bash) the API URL
8.	Go to Postman - add a new request, paste the link and click "SEND" button
9.	Go to the Idemia career page: https://careers.idemia.com/search/?createNewAlert=false&q=&locationsearch=romania&optionsFacetsDD_city=&optionsFacetsDD_customfield2=&optionsFacetsDD_customfield3=
10.	Check jobs location

EXPECTED RESULTS:
On the peviitor.ro website, there are jobs with locations from another country: Dakar(Senegal) and Courbevoie(Franta).

ACTUAL RESULT:
All job locations are in Romania.

![Untitledsdsds](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/157009443/d1bb60e7-bfc0-445e-8591-1d2bbd9a9b62)

![Untitledd](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/157009443/3d4e9c7b-69c2-4d71-9875-7890e6c73c93)

**Comment by andreireporter13** [comment]
Fixed.
