### ISSUE TITLE
Eurofins - location bug in data from Postman - County : Alba and city : Galati 

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/Scrapers_start_with_digi#319]
ENVIROMENT: production
URL: peviitor.ro
Browser: Mozilla
Device: PC
OS: Linux

**STEPS TO REPRODUCE:**

    Open URL in browser
    Type "Eurofins" in the search bar.
    Click on "Cauta" button
    Right-click and then click the Inspect option
    Click on "Network" Button
    Click on "Fetch/XHR"
    Right-click and copy as cURL(bash) the API URL
    Go to Postman - add a new request, paste the link and click "SEND" button
    Verify data of the jobs.
    Verifiy countries and cities of the jobs.

**EXPECTED RESULTS:**
All data si correct.

**ACTUAL RESULT:**
Data of the jobs (DevOps Engineer, Senior DevOps Engineer - Remote in Romania,Middle level DevOps Engineer - Remote in Romania and MS Dynamics 365 Solution Architect (SaaS and API)) is incorrect and it writes : city is Galati and county is Alba (and Alb is not the county of Galati)
![Galati, Alba](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/129604131/9f0e3569-c3b3-4e16-9890-59870b9d234b)

![Galati, Alba 2](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/129604131/0f3bc606-0e0b-4beb-8c87-995fdbcadc12)

![Galati-Alba3](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/129604131/0b07e78c-104d-48a8-b9a4-0269e8b88797)

![Galati-Alba4](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/129604131/bde3b942-c4fd-4123-869d-ebe3af5e3f0a)

**Comment by andreireporter13** [comment]
Am dat run la eurofins. Pare ca a disparut. Poti reverifica, te rog?
