### ISSUE TITLE
Blackline- The number of jobs is the same as on the company's official website

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/Scrapers_start_with_digi#327]
**Description :** After entering the company Blackline in the search bar and entered to search it, the jobs are displayed with the same number as on the company's offician website. 
**Precondition :** The website peviitor.ro is up and running

**Comment by DeedeeDL** [comment]
Step 1 : Open peviitor.ro
Expected result : You can see the homepage with the searching bar in the middle

**Comment by DeedeeDL** [comment]
Step 2: Write in the searching bar the name of the company ("Blackline"). Than click enter
Expected result  : you can write the name of the company inside the searching bar.

**Comment by DeedeeDL** [comment]
Step 3 : Verify if the jobs of the company are displayed.
Expected result : you can see the company's jobs, each job inside a box

**Comment by DeedeeDL** [comment]
Step 4 : Verify the number of the jobs.
Expected result : above the boxes with the jobs you can see the the number of jobs.

**Comment by DeedeeDL** [comment]
Step 5: Go on the company's oficial website and see if the number of the jobs is the same with the jobs number displayed on peviitor.ro
Expected result : the number of jobs from the oficisl company website is the same with the number of jobs on peviitor.ro

**Comment by aplugaru** [comment]
ENVIRONMENT: scrapers_start_with_digi

URL: [Blackline](https://peviitor.ro/#/rezultate)
         https://careers.blackline.com/careers-home/jobs?country=Romania&page=1

Browser: Chrome
Device: Laptop
OS: Windows

STEPS TO REPRODUCE:
Open URL in browser
Type "Blackline" in the search bar
press "catre site"

EXPECTED RESULTS:
the number of jobs from the official company website is the same with the number of jobs on peviitor.ro

ACTUAL RESULTS:
the number of jobs from the official company website is bigger than the number of jobs on peviitor.ro

**Comment by DeedeeDL** [comment]
Problem solved. Please retest

**Comment by aplugaru** [comment]
Retested.
