### ISSUE TITLE
Spyrosoft - The number of jobs is the same as on the company's official website

### ISSUE THREAD

**Issue by aplugaru** [peviitor-ro/Scrapers_start_with_digi#351]
**Description:** After entering the company Spyrosoft in the search bar and entered to search it, the jobs are displayed with the same title as on the company's official website.
**Precondition:** The website (https://peviitor.ro/) is up and running

**Comment by aplugaru** [comment]
**Step 1:** Open (https://peviitor.ro/)
**Expected result:** You can see the homepage with the searching bar in the middle

**Comment by aplugaru** [comment]
**Step 2:** Write in the searching bar the name of the company ("Spyrosoft"). Then click enter
**Expected result:** you can write the name of the company inside the searching bar and be redirected to the company's jobs

**Comment by aplugaru** [comment]
**Step 3:** Verify if the jobs of the company are displayed.
**Expected result:** you can see the company's jobs, each job inside a box

**Comment by aplugaru** [comment]
**Step 4:** Verify the number of the jobs.
**Expected result:** above the boxes with the jobs you can see the the number of jobs.

**Comment by aplugaru** [comment]
**Step 5:** Go on the company's official website and see if the number of the jobs is the same with the jobs number displayed on peviitor.ro
Expected result : the number of jobs from the official company website is the same with the number of jobs on peviitor.ro

**Comment by DeedeeDL** [comment]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Type "Spyrosoft" in the search bar.
Click on "Cauta" button
Verify the number of jobs
Go to the Spyrosoft career page: https://spyro-soft.com/career/sw-architect
Check the number of jobs.
**Expected result:**
The jobs are the same on both websites.
**Actual result:**
The number of jobs on peviitor.ro differs


![Image](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/129604131/6d3c10df-59d8-4077-b91d-8f71be2a4a31)



![Image](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/129604131/38bcb5cc-4be4-4921-b330-bae178937342)

**Comment by DeedeeDL** [comment]
Retested. PASS
