### ISSUE TITLE
Conectys - The titles of jobs are the same as on the company's official website

### ISSUE THREAD

**Issue by aplugaru** [peviitor-ro/Scrapers_start_with_digi#358]
**Description:** After entering the company Conectys in the search bar and entered to search it, the jobs are displayed with the same title as on the company's official website.
**Precondition:** The website (https://peviitor.ro) is up and running

**Comment by aplugaru** [comment]
**Step 1:** Write in the searching bar the name of the company ("Conectys"). Then click enter
**Expected result:** you can write the name of the company inside the searching bar and you can click enter

**Comment by aplugaru** [comment]
**Step 2:** Verify if the jobs of the company are displayed.
**Expected result:** you can see the company's jobs, each job inside a box

**Comment by aplugaru** [comment]
**Step 4:** Verify the title of the jobs.
**Expected result:** inside the boxes with the jobs, the titles are displayed.

**Comment by aplugaru** [comment]
**Step 5:** Go on the company's official website and see if the titles of the jobs are the same with the job titles displayed on peviitor.ro
**Expected result :** the title of jobs from the official company website are the same with the titles of the jobs on peviitor.ro

**Comment by DeedeeDL** [comment]
All tests passed
