### ISSUE TITLE
Redbeesoftware - Verify if the location of the jobs are displayed

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/Scrapers_start_with_digi#362]
**Description :**  On production (https://peviitor.ro) all the jobs are displayed alongside their locations)
**Precondition:** The website is up and running

**Comment by DeedeeDL** [comment]
Step 1 : Open the URL (https://peviitor.ro)
Expected result : The homepage is displayed

**Comment by Omiale** [comment]
Step 2 : Verify if the searching bar is functional by clicking inside it.
Expected result : The text can be typed inside the searching bar

**Comment by Omiale** [comment]
Step 3 : Verify that under the jobs name the location is displayed(exemple : Cluj-Napoca)
Expected result : The job location is displayed under the job name
