### ISSUE TITLE
Dornamedical - The company can be found on production when the name of the company is typed in the searching bar

### ISSUE THREAD

**Issue by Omiale** [peviitor-ro/Scrapers_start_with_digi#363]
Description : The company Dornamedical can be found on https://peviitor.ro/ after the name of the company was typed in the searching bar.
Expected result : The website https://peviitor.ro/ is up and running

**Comment by Omiale** [comment]
Step 1 : Open the homepage of the URL (https://peviitor.ro/)
Expected result : In the middle of the homepage is a searching bar

**Comment by Omiale** [comment]
Step 2 : Verify if the searching bar is functional by clicking inside it.
Expected result : The text can be typed inside the searching bar

**Comment by Omiale** [comment]
Step 4 : After typing the company's name press ENTER or click on the button CAUTA next to the searching bar
Expected result : After entering the company is found and displayed alongside its jobs.

**Comment by DeedeeDL** [comment]
Tests passed
