### ISSUE TITLE
TC 1 - Cec Bank company is displayed on production

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/Scrapers_start_with_digi#380]
Description :  Verify if the company Cec Bank can be find on peviitor.ro
Precondition: The website (https://peviitor.ro/) is up and running

**Comment by aplugaru** [comment]
**Step 1 :** Go to the search bar and see if it is editable by clicking inside of it.
**Expected result :** The search bar is editable and functional and you can write any text inside it.

**Comment by aplugaru** [comment]
**Step 2:** Type in the searching bar the name of the company ("Cec Bank"). Then click enter
**Expected result:** you can write the name of the company inside the searching bar and be redirected to the company's jobs

**Comment by aplugaru** [comment]
Stept 3: When redirected to the next page, check if the company Cec Bank appears in production with jobs
Expected results: the company Cec Bank appears in production
