### ISSUE TITLE
Funcom - The titles of jobs are the same as on the company's official website

### ISSUE THREAD

**Issue by aplugaru** [peviitor-ro/Scrapers_start_with_digi#389]
**Description:** After entering the company Funcom in the search bar and entered to search it, the jobs are displayed with the same title as on the company's official website.
**Precondition:** The website (https://peviitor.ro/) is up and running

**Comment by aplugaru** [comment]
**Step 1:** Write in the searching bar the name of the company ("Funcom"). Then click enter
**Expected result:** you can write the name of the company inside the search bar and you can click enter

**Comment by aplugaru** [comment]
**Step 2:** Verify if the jobs of the company are displayed.
**Expected result:** you can see the company's jobs, each job inside a box

**Comment by aplugaru** [comment]
**Step 3:** Verify the title of the jobs.
**Expected result:** inside the boxes with the jobs the titles are displayed.

**Comment by DeedeeDL** [comment]
@aplugaru first, you need to fix the number of jobs, clicking the button "Sincronizeaza joburile" from validator
