### ISSUE TITLE
The description of company appears with an other name.

### ISSUE THREAD

**Issue by talmacelanamaria** [peviitor-ro/Scrapers_start_with_digi#398]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Search for company "TotalSoft"
3.Click on "Vizualizeaza joburi"

EXPECTED RESULTS:
The description of company must be same with the name of company.

ACTUAL RESULTS:
The description of company appears with an other name.
![Captură de ecran 2024-09-26 085306](https://github.com/user-attachments/assets/5df744d1-d19c-4289-836b-f501bf97685c)
![Captură de ecran 2024-09-26 103103](https://github.com/user-attachments/assets/4fd5c5dc-5902-402a-b6b8-86d4ae2d18de)

**Comment by andreireporter13** [comment]
E doar un singur job care are aceasta problema????

**Comment by andreireporter13** [comment]
Intrebarea e alta, vine de TotalSoft jobul?
