### ISSUE TITLE
The name of the city is not same with description.

### ISSUE THREAD

**Issue by talmacelanamaria** [peviitor-ro/Scrapers_start_with_digi#399]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Search for company "Smarttech"
3.Click on "Vizualizeaza joburi"

EXPECTED RESULTS:
The name of the city must be same with description.

ACTUAL RESULTS:
The name of the city is not same with description.
![Captură de ecran 2024-10-01 184226](https://github.com/user-attachments/assets/edca6897-95eb-4d67-8d81-69bf70a514ca)
![Captură de ecran 2024-10-01 184259](https://github.com/user-attachments/assets/38da761b-8d13-4e5f-a941-68f8c87601f9)

**Comment by andreireporter13** [comment]
Aici au fost harcodate. :))))
