### ISSUE TITLE
The name of the job is not in description of title 

### ISSUE THREAD

**Issue by talmacelanamaria** [peviitor-ro/Scrapers_start_with_digi#400]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Search for company "SAP"
3.Click on "Vizualizeaza joburi"

EXPECTED RESULTS:
The name of the job must be in description of title.

ACTUAL RESULTS:
The name of the job is not in description  of title
![Captură de ecran 2024-10-03 124732](https://github.com/user-attachments/assets/7a01a88d-165f-47a5-acc5-7b8f75d54552)

**Comment by andreireporter13** [comment]
Mai sunt joburi pe SAP?

**Comment by talmacelanamaria** [comment]
68 de joburi , din care 67 publicate,

În sâm., 5 oct. 2024 la 20:40, Andrei Cojocaru ***@***.***> a
scris:

**Comment by andreireporter13** [comment]
![image](https://github.com/user-attachments/assets/20e66929-3de8-4acd-a107-b697bdc18054)
