### ISSUE TITLE
we have diferent number of jobs on firme.peviitor.ro for Capex Company then scrapers.peviitor.ro

### ISSUE THREAD

**Issue by BogdanScutariu** [peviitor-ro/Scrapers_start_with_digi#43]
ENVIRONMENT: windows
URL: https://peviitor.ro/rezultate?q=CAPEX&country=Rom%C3%A2nia&page=1
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2. Search Capex Company 
3. look at the jobs 

Expected results : we should have 11 jobs 
![Screenshot (33)](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/139114218/55fc7396-71e9-4599-97ef-34b89dfebcf7)

Actual results: we have 14 jobs. 
those 3 jobs is not supposed to be on this site:
1. Procurement Leader
Alstom
map pinRomânia
url:https://jobsearch.alstom.com/job/Bucharest-Capex-Procurement-Leader-B/918939601/
2.Working Student – Finance/Commercial Equipment and Transport (CAPEX)
![Screenshot (35)](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/139114218/d8a54629-2c05-4305-b89d-9347387b9485)

SiemensEnergy
map pinRomânia
url:https://jobs.siemens-energy.com/en_US/jobs/FolderDetail/Working-Student-Finance-Commercial-Equipment-and-Transport-CAPEX/250673
3. Senior Sourcing Lead with German (Capex, MRO)
GEP
map pinRomânia
url: https://jobseurope-gep.icims.com/jobs/29297/senior-sourcing-lead-with-german-%28capex%2c-mro%29/job
![Screenshot (34)](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/139114218/53c7db62-7917-45f5-9398-835093a5bff4)

**Comment by danielastanculesc** [comment]
I also found a job that does not belong to the Capex company.
![capex](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/143128512/3158e4d2-cdd2-4725-a8b9-b6aa30fbb3a8)
