### ISSUE TITLE
Wrong name in the name of the city where the job is located

### ISSUE THREAD

**Issue by LauraScutariu** [peviitor-ro/Scrapers_start_with_digi#45]
ENVIRONMENT: MacBook Air
URL: https://scrapers.peviitor.ro/src/yokogawa/index.html
Browser: Chrome

STEPS TO REPRODUCE:
1)Open url in the browser;
2)Type "Yokogawa" in the search bar;
3)Click on Yokogawa
<img width="1440" alt="Captură de ecran din 2023-10-11 la 16 42 56" src="https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/138318963/38d6dd85-f129-42c4-8b44-9a417b3462cd">

**Comment by andreireporter13** [comment]
Reparat, partial.
