### ISSUE TITLE
Unknown name when naming the job type

### ISSUE THREAD

**Issue by LauraScutariu** [peviitor-ro/Scrapers_start_with_digi#46]
ENVIRONMENT: MacBook Air
URL: https://scrapers.peviitor.ro/src/xperi/index.html
Browser: Chrome

STEPS TO REPRODUCE:
1)Open url in the browser;
2)Type "Xperi" in the search bar;
3)Click on Xperi
<img width="1440" alt="Captură de ecran din 2023-10-11 la 16 50 54" src="https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/138318963/cb6708dc-7fbd-4aa5-bbb9-5f6dc5a98715">

**Comment by andreireporter13** [comment]
No mandatory.
