### ISSUE TITLE
Egger - missing city

### ISSUE THREAD

**Issue by thinkinbro** [peviitor-ro/Scrapers_start_with_digi#53]
Enviroment: Production
Browser: Chrome
Url:  scrapers.peviitor.ro

Pasi de reproducere:
1) Acceseaza Url
2) Verifica orasul joburilor

Rezultate asteptate:
Orasul afisat corect  la fiecare job

Rezultate actuale:
Orasul nu este afisat

![Screenshot 2023-10-13 203403](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/97815419/8ab30c17-588b-4a14-bb79-c5b5cce50c26)

**Comment by danielastanculesc** [comment]
Same result.
