### ISSUE TITLE
Only 30 jobs available for AECOM on peviitor.ro, whilst 36 on their website 

### ISSUE THREAD

**Issue by AleOstas** [peviitor-ro/Scrapers_start_with_digi#58]
Enviroment: MacBook Pro
URL: https://scrapers.peviitor.ro/src/aecom/index.html
Browser: Chrome

STEPS TO REPRODUCE:
1. Open url in Chrome browser
2. Run scraper
3. Check number of jobs in comparison to the AECOM careers.

Expected results

Should have 36 jobs available in Romania
<img width="1058" alt="Screenshot 2023-10-20 at 16 44 25" src="https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/73651307/68f75b89-8b52-4640-b284-7a0b7a3565d7">

Actual results

Only have 30
<img width="1130" alt="Screenshot 2023-10-20 at 16 45 20" src="https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/73651307/e543feaa-d31a-4d79-8c15-c543d064c660">

**Comment by andreireporter13** [comment]
Done! Refacut!
