### ISSUE TITLE
On firme.peviitor.ro we have 2 times the same "Cegedin"company

### ISSUE THREAD

**Issue by BogdanScutariu** [peviitor-ro/Scrapers_start_with_digi#66]
ENVIRONMENT: windows
URL: https://firme.peviitor.ro/
Browser: chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

Open the URL in the browser
1.We open browser
2.We insert the url
3.we write "Cegedim" company

Expected results: We should have only one company with "Cegedim "Company 

Actual results: We have 2 Company with the same name "Cegedim"
![Screenshot (38)](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/139114218/23e006d0-ac7d-45dc-90b3-ec81523d762f)

**Comment by lalalaurentiu** [comment]
Fixed!
