### ISSUE TITLE
We have 2 times "Citi Company" on firme.peviitor.ro

### ISSUE THREAD

**Issue by BogdanScutariu** [peviitor-ro/Scrapers_start_with_digi#69]
ENVIRONMENT: windows
URL: https://firme.peviitor.ro/
Browser: chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

Open the URL in the browser
1.We open browser
2.We insert the url
3.we write "Citi" company

Expected results: We schould have only one company with "Citi"Company

Actual results: We have 2 Company with the same name "Citi"
![Screenshot (43)](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/139114218/b2a682ce-2c66-492b-b1bb-7446de3ffe7f)

**Comment by danielastanculesc** [comment]
Same result.
