### ISSUE TITLE
we have 2 "Clevertech company" on firme.peviitor.ro and should be only one 

### ISSUE THREAD

**Issue by BogdanScutariu** [peviitor-ro/Scrapers_start_with_digi#70]
ENVIRONMENT: windows
URL: https://firme.peviitor.ro/
Browser: chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

Open the URL in the browser
1.We open browser
2.We insert the url
3.we write "Clevertech" company

Expected results: We schould have only one company with "Clevertech "Company

Actual results: We have 2 Company with the same name "Clevertech"
![Screenshot (44)](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/139114218/0eaf81dc-4f25-4962-b51f-7ef20cd11fe5)
"

**Comment by lalalaurentiu** [comment]
Fixed!
