### ISSUE TITLE
On the scrapers.peviitor.ro we have the name of the city for : "Clevertech Company" we have next message: Remote is not a city from Romania 

### ISSUE THREAD

**Issue by BogdanScutariu** [peviitor-ro/Scrapers_start_with_digi#71]
ENVIRONMENT: windows
URL: https://scrapers.peviitor.ro/src/clevertech/index.html
Browser: chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

Open the URL in the browser
1.We open browser
2.We insert the url
3.we write "Clevertech" company
4.we run the scraper

Expected results: We should have city names or remote job

Actual results: We have the next message for all jobs: "Remote is not a city from  Romania"
![Screenshot (45)](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/139114218/278b34f9-0438-4832-81a6-baba8ed81fe4)

**Comment by lalalaurentiu** [comment]
@andreireporter13 este screperul tău!

**Comment by andreireporter13** [comment]
Imediat il rezolv.
