### ISSUE TITLE
We have 2 company with the same names on firme.peviitor.ro for "Conectys "

### ISSUE THREAD

**Issue by BogdanScutariu** [peviitor-ro/Scrapers_start_with_digi#72]
ENVIRONMENT: windows
URL: https://firme.peviitor.ro/
Browser: chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

Open the URL in the browser
1.We open browser
2.We insert the url
3.we write "Conetys" company

Expected results: We schould have only one company with "Conectys"Company

Actual results: We have 2 Company with the same name "Conectys
![Screenshot (46)](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/139114218/bf2140dd-280b-4c5c-926a-b85920576d0a)
"

**Comment by lalalaurentiu** [comment]
Fixed!
