### ISSUE TITLE
"Connect44 Company does not exist on firme.peviitor.ro

### ISSUE THREAD

**Issue by BogdanScutariu** [peviitor-ro/Scrapers_start_with_digi#73]
ENVIRONMENT: windows
URL: https://firme.peviitor.ro/
Browser: chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

Open the URL in the browser
1.We open browser
2.We insert the url
3.we write "Connect44" company

Expected results: We should have a result with company jobs 

Actual results: We dont have any results for this company
![Screenshot (48)](https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/139114218/8a21b55e-df8a-4644-a5d4-0242c5e61ea8)

**Comment by lalalaurentiu** [comment]
Hai ca m-am murdărit destul de engleză la gura :)), o dau pe română. @andreireporter13 vezi ca pentru connect44 nu. ai adăugat logo în baza de date și de acea nu apare-n firme.peviitor.ro.
<img width="1440" alt="Screenshot 2023-10-22 at 13 36 22" src="https://github.com/peviitor-ro/Scrapers_start_with_digi/assets/67306273/1ca60680-5045-49c6-b894-00aff08a9bad">

**Comment by danielastanculesc** [comment]
Same result.
